# Generated by Django 2.0.9 on 2018-10-06 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(choices=[('lab01', 'Laboratório - 01'), ('lab02', 'Laboratório - 02'), ('lab03', 'Laboratório - 03'), ('lab04', 'Laboratório - 04'), ('lab05', 'Laboratório - 05'), ('lab06', 'Laboratório - 06'), ('lab07', 'Laboratório - 07'), ('lab08', 'Laboratório - 08'), ('lab09', 'Laboratório - 09'), ('lab10', 'Laboratório - 10')], max_length=2)),
                ('course', models.CharField(choices=[('01', 'Adminstração'), ('02', 'Ciências Contábeis'), ('03', 'Educação Fisica'), ('04', 'Enfermagem'), ('05', 'Farmácia'), ('06', 'Fisioterapia'), ('07', 'Gastronimia'), ('08', 'Recursos Humanos'), ('09', 'Psicologia')], max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('period', models.CharField(choices=[('01', 'Matutino'), ('02', 'Noturno')], max_length=2)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
