# Generated by Django 2.0.9 on 2018-10-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='lab',
            field=models.CharField(choices=[('01', 'Laboratório - 01'), ('02', 'Laboratório - 02'), ('03', 'Laboratório - 03'), ('04', 'Laboratório - 04'), ('05', 'Laboratório - 05'), ('06', 'Laboratório - 06'), ('07', 'Laboratório - 07'), ('08', 'Laboratório - 08'), ('09', 'Laboratório - 09'), ('10', 'Laboratório - 10')], max_length=2),
        ),
    ]
