# Generated by Django 2.0.9 on 2018-10-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181008_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2)),
                ('name', models.CharField(choices=[('01', 'Adminstração'), ('02', 'Ciências Contábeis'), ('03', 'Educação Fisica'), ('04', 'Enfermagem'), ('05', 'Farmácia'), ('06', 'Fisioterapia'), ('07', 'Gastronimia'), ('08', 'Recursos Humanos'), ('09', 'Psicologia')], max_length=200)),
            ],
        ),
    ]
