# Generated by Django 2.0.9 on 2018-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='lab',
            field=models.CharField(choices=[('Laboratório - 01', 'Laboratório - 01'), ('Laboratório - 02', 'Laboratório - 02'), ('Laboratório - 03', 'Laboratório - 03'), ('Laboratório - 04', 'Laboratório - 04'), ('Laboratório - 05', 'Laboratório - 05'), ('Laboratório - 06', 'Laboratório - 06'), ('Laboratório - 07', 'Laboratório - 07'), ('Laboratório - 08', 'Laboratório - 08'), ('Laboratório - 09', 'Laboratório - 09'), ('Laboratório - 10', 'Laboratório - 10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='period',
            field=models.CharField(max_length=2),
        ),
    ]
