# Generated by Django 2.0.9 on 2018-10-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181008_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unidade',
            field=models.CharField(choices=[('1', 'VG'), ('2', 'CS')], default=1, max_length=2, verbose_name='Unidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='lab',
            field=models.CharField(max_length=2),
        ),
    ]
