# Generated by Django 2.0.9 on 2018-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181015_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.TextField(default='Teste', max_length=250, verbose_name='Detalhes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.CharField(max_length=2, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lab',
            field=models.CharField(max_length=2, verbose_name='Laboratório'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='post',
            name='period',
            field=models.CharField(max_length=2, verbose_name='Periodo'),
        ),
    ]
