# Generated by Django 2.0.9 on 2018-10-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181030_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(max_length=150, verbose_name='Detalhes'),
        ),
    ]
