# Generated by Django 2.0.9 on 2018-10-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181030_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='period',
            field=models.CharField(max_length=2, unique_for_date='create_date', verbose_name='Periodo'),
        ),
    ]
