# Generated by Django 2.0.9 on 2018-10-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181030_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lab',
            field=models.CharField(max_length=2, verbose_name='Laboratório'),
        ),
    ]
