# Generated by Django 2.0.9 on 2018-12-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181030_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='data_course',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(help_text='Descreva os detalhes do agendamento com até 120 caracteres, obrigado!', max_length=150, verbose_name='Detalhes'),
        ),
    ]
