# Generated by Django 2.0.9 on 2019-02-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190218_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.CharField(max_length=2, verbose_name='Curso'),
        ),
    ]
