# Generated by Django 2.0.9 on 2019-02-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='linha1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linha2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento'),
        ),
    ]
